var k="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},l;if("function"==typeof Object.setPrototypeOf)l=Object.setPrototypeOf;else{var m;a:{var n={o:!0},p={};try{p.__proto__=n;m=p.o;break a}catch(a){}m=!1}l=m?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var q=l;function r(){this.l=!0;this.a=new t}
r.prototype.j=function(a){for(var b=this.a,c=0;c<a.length;c++){var f=a.charAt(c),d=u(b,f,!0);void 0==d&&(d=new t(b.depth+1),b.h.set(f,d));b=d}b.c.add(a)};r.prototype.getState=function(a,b){for(var c=u(a,b,!1);void 0==c;)a=a.b,c=u(a,b,!1);return c};function v(a,b,c){return new x(b.substring(c+1,null==a?b.length:a.start),void 0)}function y(){this.i=new r}function z(){var a=new y;a.i.l=!1;return a}y.prototype.j=function(a){this.i.j(a);return this};
function A(a){for(var b=[],c=a.i.a,f=Array.from(c.h.values()),d=0;d<f.length;d++){var e=f[d];e.b=c;b.push(e)}for(;0!=b.length;)for(c=b.shift(),f=Array.from(c.h.keys()),d=0;d<f.length;d++){var g=f[d];e=u(c,g,!1);b.push(e);for(var h=c.b;null==u(h,g,!1);)h=h.b;g=u(h,g,!1);e.b=g;g=Array.from(g.c.values());for(h=0;h<g.length;h++)e.c.add(g[h])}return a.i}function t(a){a=void 0===a?0:a;this.a=null;this.h=new Map;this.b=null;this.c=new Set;this.depth=a;this.a=0==a?this:null}
function u(a,b,c){b=a.h.get(b);c||void 0!=b||null==a.a||(b=a.a);return b}function B(a,b){this.start=a;this.end=b}B.prototype.size=function(){return this.end-this.start+1};function C(a,b){B.call(this,a,b)}C.prototype=k(B.prototype);C.prototype.constructor=C;if(q)q(C,B);else for(var D in B)if("prototype"!=D)if(Object.defineProperties){var E=Object.getOwnPropertyDescriptor(B,D);E&&Object.defineProperty(C,D,E)}else C[D]=B[D];C.v=B.prototype;function x(a,b){this.m=a;this.match=void 0!=b}
function F(a){this.s=new G(a)}function H(a,b){b.sort(function(b,a){var c=a.size()-b.size();0==c&&(c=b.start-a.start);return c});for(var c=new Set,f=0;f<b.length;f++){var d=b[f];c.has(d)||I(a.s,d).forEach(function(b){return c.add(b)})}b=b.filter(function(b){return!c.has(b)});b.sort(function(b,a){return b.start-a.start});return b}
function G(a){this.right=this.left=null;this.f=[];for(var b=-1,c=-1,f=0;f<a.length;f++){var d=a[f],e=d.start;d=d.end;if(-1==b||e<b)b=e;if(-1==c||d>c)c=d}this.g=(b+c)/2;b=[];c=[];for(f=0;f<a.length;f++)e=a[f],e.end<this.g?b.push(e):e.start>this.g?c.push(e):this.f.push(e);0<b.length&&(this.left=new G(b));0<c.length&&(this.right=new G(c))}
function I(a,b){var c=[];a.g<b.start?(J(b,c,K(a.right,b)),J(b,c,L(a,b,1))):a.g>b.end?(J(b,c,K(a.left,b)),J(b,c,L(a,b,-1))):(J(b,c,a.f),J(b,c,K(a.left,b)),J(b,c,K(a.right,b)));return c}function J(a,b,c){for(var f=0;f<c.length;f++){var d=c[f];d!=a&&b.push(d)}}function L(a,b,c){for(var f=[],d=0;d<a.f.length;d++){var e=a.f[d];-1==c&&e.start<=b.end&&f.push(e);1==c&&e.end>=b.start&&f.push(e)}return f}function K(a,b){return null==a?[]:I(a,b)}
angular.module("weechat").filter("gbs_smileys",function(){var a=z();Object.keys(smileys_directory).forEach(function(b){a.j(b)});var b=A(a);return function(a){var c=[];var d=[];for(var e=b.a,g=0;g<a.length;g++){e=b.getState(e,a.charAt(g));for(var h=Array.from(e.c.values()),w=0;w<h.length;w++)d.push(new C(g-h[w].length+1,g))}b.l||(d=H(new F(d),d));g=-1;for(e=0;e<d.length;e++)1<d[e].start-g&&c.push(v(d[e],a,g)),g=d[e],c.push(new x(a.substring(g.start,g.end+1),g)),g=d[e].end;1<a.length-g&&c.push(v(null,a,
g));a=[];for(d=0;d<c.length;d++)e=c[d],e.match?a.push('<img src="smileys/'+smileys_directory[e.m]+'" title="'+e.m+'">'):a.push(e.m);return a.join("")}});
